### ISSUE TITLE
[Errno 13] Permission denied: '/temp'

### ISSUE THREAD

**Issue by cestevens1987** [petemc89/craXcel-cli#1]
when I run the code I get the following error. I've tried to trouble shoot and I believe it has something to do with my file permissions which are read and write as far as I can tell. I'm using a mac. 

I'm a novice. I'm running this within the terminal environment in pycharm

**Comment by cophth** [comment]
remove the / before '/temp' and it works

**Comment by petemc89** [comment]
Thanks for the feedback @cestevens1987 - I hadn't run it on a mac before so it's valuable to know it fails. 

I'll keep the issue open while I address it, but in the mean time did @cophth's workaround do the trick?

**Comment by cestevens1987** [comment]
it did!

**Comment by petemc89** [comment]
I've updated the application quite substantially now and have run my own tests on a Mac to check for compatibility, all seems to work fine but do let me know if you still have 'out-of-the-box' issues.
