### ISSUE TITLE
help : turn off xlsx worksheet protection function

### ISSUE THREAD

**Issue by newbie9188** [petemc89/craXcel-cli#13]
Hi 

I would like to open an excel file and disable the worksheet protection as in the picture. 

I have downloaded the craXcel.py file but have no clue how to start to unlock the excel via python. 
Since all of the worksheet is protected therefore pd.read_excel and openpyxl.load_workbook('NXTS122ND8S10.xlsx')  cannot read the excel. 

Any help would be appreciated.  

Thank you. 

[NXTS122ND8S10.xlsx](https://github.com/petemc89/craXcel-cli/files/6174847/NXTS122ND8S10.xlsx)
![image](https://user-images.githubusercontent.com/80660132/111858266-fbfa5800-890d-11eb-9f71-5838eab22cd9.png)

**Comment by petemc89** [comment]
Hi there.

Is the problem that you're not sure how to use python/command-line applications?

If so, what you need to do is:

1. Download Python https://www.python.org/downloads/
2. Clone this repository (downloading zip might be easiest - https://github.com/petemc89/craXcel-cli/archive/refs/heads/master.zip)
3. Put your file in the folder with the code
4. Open a command line (cmd, powershell etc)
5. Type: **python craxcel.py name-of-file.xlsx**

Ooooor, you can use www.craxcel.com and not have to worry about any of that :)

**Comment by newbie9188** [comment]
Hi, 

I will follow the instruction. 

Thank you for your help.
