### ISSUE TITLE
Overwrite original document

### ISSUE THREAD

**Issue by oobug** [petemc89/craXcel-cli#8]
My expectation when using this utility is that I will be unlocking my original document. Instead of creating a new document in the "unlocked" directory, the default behavior should be to overwrite the original document.

To handle scenarios in which the original document should be maintained, I would also suggest adding some sort of "--preserve" flag to keep the original documents around.

**Comment by petemc89** [comment]
Hmm... This was a consideration of mine when designing the tool, however I was hesitant to make it destructive by default and decided an unlocked copy was the way to go. 

I do like the idea of introducing a flag to allow the user to decide though. As I'm pretty sold on keeping it non-destructive by default this would look something like "--overwrite". I'll introduce this the next time I work on the project.
