### ISSUE TITLE
Transparently create temporary directories

### ISSUE THREAD

**Issue by oobug** [petemc89/craXcel-cli#9]
Currently, craXcel is creating "temp" and "unlocked" directories in the current directory of the file being unlocked. Instead, this should use tempfile to transparently create temporary directories and remove them once they are no longer needed.

**Comment by petemc89** [comment]
Hi there! So sorry for the late reply. Thanks for the feedback, makes complete sense to go the route you've suggested. I will incorporate the next time I work on the project.
